#!/bin/sh /etc/rc.common
# Copyright 2024 Wan

USE_PROCD=1
START=99

PROG="/usr/local/bin/ipv6"
STOP=1

start_service() {
  procd_open_instance
  procd_set_param command "$PROG"

  # -addr [<address>]:<port> listen on IP address <address> with optional <port>
  procd_append_param command -addr :9090

  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

restart() {
  stop
  start
}
